version: '3.8' # 虽然已过时但可以保留

services:
  web:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data
    networks:
      - app-net
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
